# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Apps in vellum
tagline:          'Information technologies in ancient Greek scholarship'
description:      ''

baseurl: ''


author:
  name:           'Neel Smith'


paginate:         5


links:
  - title: Github repository for this web site
    url: https://github.com/appsinvellum/appsinvellum.github.io
    external: true
